// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzP6He4Vx07wWxz_4lCtyLGwytL9NqPRQ',
    appId: '1:72643442470:web:2597afffc09a6b1bf533e7',
    messagingSenderId: '72643442470',
    projectId: 'appflutter-4b51a',
    authDomain: 'appflutter-4b51a.firebaseapp.com',
    storageBucket: 'appflutter-4b51a.appspot.com',
    measurementId: 'G-NVC5WYBJCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxkOSJgi_2Xgn20ns-0dfAAVRBBxJRHEE',
    appId: '1:72643442470:android:a5a3edc4a18266a7f533e7',
    messagingSenderId: '72643442470',
    projectId: 'appflutter-4b51a',
    storageBucket: 'appflutter-4b51a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwqB_kgAi5fIbSb7hn0S_bXdBm9BNLrkw',
    appId: '1:72643442470:ios:bdf853f7e02bc7e8f533e7',
    messagingSenderId: '72643442470',
    projectId: 'appflutter-4b51a',
    storageBucket: 'appflutter-4b51a.appspot.com',
    iosBundleId: 'com.example.appfiepa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwqB_kgAi5fIbSb7hn0S_bXdBm9BNLrkw',
    appId: '1:72643442470:ios:ebc487e52af49975f533e7',
    messagingSenderId: '72643442470',
    projectId: 'appflutter-4b51a',
    storageBucket: 'appflutter-4b51a.appspot.com',
    iosBundleId: 'com.example.appfiepa.RunnerTests',
  );
}
